version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: ideo_backend_task
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_ROOT_PASSWORD: admin
      # POSTGRES_DATABASE: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: backendPassword
    ports:
      - 5300:5432 # Host port 5400 mapped to container's port 5432
  # volumes:
  # backend_db_Postgres_data: # Volume to persist Postgres data
